# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: foreman-installer.spec

# add or remove files that should be synced
files_to_sync:
    - foreman-installer.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: foreman-installer
# downstream (Fedora) RPM package name
downstream_package_name: foreman-installer

upstream_tag_template: "{version}"

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/foreman/foreman-installer/foreman-installer.spec -O foreman-installer.spec"
  get-current-version:
    - "sed 's/-develop//' VERSION"
  create-archive:
    - bundle config set --local path vendor/bundle
    - bundle config set --local without development:test
    - bundle install
    - bundle exec rake pkg:generate_source
    - bash -c "ls -1t pkg/*.tar.bz2 | head -n 1"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      centos-stream-8:
        additional_modules: "foreman:el8"
        additional_repos:
          - http://koji.katello.org/releases/yum/foreman-nightly/el8/x86_64/
          - http://yum.puppet.com/puppet7/el/8/x86_64/
    module_hotfixes: true

srpm_build_deps:
  - wget
  - make
  - gcc
  - ruby
  - ruby-devel
  - rubygem-bundler
