AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - '_build/**/*'
    - 'pkg/**/*'
    - 'Gemfile'
    - 'Puppetfile'

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce certain methods, e.g. detect over find
Style/CollectionMethods:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

#Allow both ['a', 'b'], %w[a b] and %w(a b) style arrays
Style/WordArray:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/InverseMethods:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Layout/DotPosition:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

# disabled until we can configure "+" as concat sign
Style/LineEndConcatenation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

# Won't work with sqlite
Style/MultipleComparison:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
