#!/bin/bash

for d in modules/*; do
  [ -d $d ] || continue
  [ -e $d/Modulefile ] || continue
  egrep -q "^name.*theforeman" $d/Modulefile || continue
  pushd $d
  if ! puppet module build .; then
    echo "ERROR: failed to build $d" >&2
    exit 1
  fi
  popd
done

[ -d pkg ] || mkdir pkg
mv modules/*/pkg/theforeman*gz pkg/

exit 0
