#!/bin/bash
#
# bump_modules 1.3.0 1.4.0-rc1
#
[ -z "$1" -o -z "$2" ] && echo "Usage: $0 from to" && exit

for MODFILE in $(grep source modules/*/Modulefile | grep theforeman | awk -F':' '{ print $1 }'); do
  echo Working on $MODFILE
  pushd $(dirname $MODFILE)
  git checkout master && \
  git pull && \
  sed -i "s/$1/$2/" $(basename $MODFILE) && \
  git diff && \
  echo "Okay to commit and push? (ENTER or Ctrl-C)" && read && \
  git commit -a -m "Release $2" && git pull --rebase && git push origin master
  popd
done
