forge 'https://forgeapi.puppet.com/'

mod 'puppetlabs/apache',               '>= 8.3'
mod 'puppetlabs/postgresql',           '>= 10.1'
mod 'puppet/redis',                    '>= 8.5.0'
mod 'puppetlabs/vcsrepo',              '>= 5.2.0'
mod 'puppet/systemd',                  '< 8'
mod 'theforeman/dhcp',                 '~> 9.3.0'
mod 'theforeman/dns',                  '~> 11.1.0'
mod 'theforeman/puppetserver_foreman', '~> 4.2.2'
mod 'theforeman/tftp',                 '~> 10.0.0'
mod 'katello/candlepin',               '~> 16.3.0'
mod 'theforeman/pulpcore',             '~> 13.1.0'
mod 'theforeman/foreman',              '~> 27.1.0'
mod 'theforeman/foreman_proxy',        '~> 28.2.0'
mod 'theforeman/puppet',               '~> 21.1.0'
mod 'katello/foreman_proxy_content',   '~> 31.2.0'
mod 'katello/certs',                   '~> 21.1.0'
mod 'katello/katello',                 '~> 26.2.0'
mod 'theforeman/iop',                  '~> 0.4.0'
mod 'southalc/podman',                 :git => 'https://github.com/southalc/podman', :tag => '0.7.13'
