#!/bin/bash
#
# simple script to create a release without tito
# it works in-place, so take care!
#
# Usage: release 1.2 el6
#

[ -z "$1" -o -z "$2" ] && echo "Usage: release version_tag dist" && exit 42

PROJECT=foreman-installer
VERSION=$1
DIST=$2

git describe $VERSION >/dev/null || echo "WARNING! There is no such tag: $VERSION!"

RPMBUILD=$(pwd)/pkg/rpmbuild
TEMPDIR=$(mktemp -d)
trap "rm -rf $TEMPDIR" EXIT
mkdir -p $TEMPDIR/$PROJECT-$VERSION $RPMBUILD/SOURCES
cp -Rad . $TEMPDIR/$PROJECT-$VERSION

pushd $TEMPDIR
rm -rf `find -name ".git*"`
tar c $PROJECT-$VERSION | gzip -9 > $RPMBUILD/SOURCES/$PROJECT-$VERSION.tar.gz
cd $PROJECT-$VERSION
rpmbuild -bs $PROJECT.spec --define "dist $DIST" --define "_topdir $RPMBUILD"
popd
