---
apache::mod::event::serverlimit: 64
apache::mod::event::maxrequestworkers: 1024
apache::mod::event::maxrequestsperchild: 4000

candlepin::java_opts: "-Xms1024m -Xmx8192m"

postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 16GB
  work_mem: 8MB
  effective_cache_size: 32GB
  autovacuum_vacuum_cost_limit: 2000
