---
apache::mod::passenger::passenger_max_pool_size: 60
apache::mod::passenger::passenger_max_request_queue_size: 1000

apache::mod::prefork::serverlimit: 1024
apache::mod::prefork::maxclients: 1024
apache::mod::prefork::maxrequestsperchild: 4000

postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 8GB
  effective_cache_size: 16GB
  autovacuum_vacuum_cost_limit: 2000
