---
apache::mod::event::serverlimit: 64
apache::mod::event::maxrequestworkers: 1024

postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 8GB
  effective_cache_size: 16GB
  autovacuum_vacuum_cost_limit: 2000
