---
apache::mod::ssl::ssl_ciper: 'PROFILE=system'
# TODO: depends on https://github.com/puppetlabs/puppetlabs-apache/pull/2335
apache::mod::ssl::ssl_proxy_ciper_suite: 'PROFILE=system'
# EL8 doesn't have support for SSLv3 anymore and errors out on it. This
# overrides security.yaml
apache::mod::ssl::ssl_protocol:
  - 'ALL'
  - '-TLSv1'
  - '-TLSv1.1'

postgresql::globals::manage_dnf_module: true
postgresql::globals::version: "12"
