# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# Every support plugin/compute class is listed, so that it
# shows up in the interactive menu
#
# See params.pp in each class for what options are available
---
foreman_proxy:
  custom_repo: true
  puppetca: true
  http: true
  http_port: '8000'
  ssl_port: '9090'
  register_in_foreman: true
  templates: true
  tftp: false
  ssl_ca: /etc/foreman-proxy/ssl_ca.pem
  ssl_cert: /etc/foreman-proxy/ssl_cert.pem
  ssl_key: /etc/foreman-proxy/ssl_key.pem
  foreman_ssl_ca: /etc/foreman-proxy/foreman_ssl_ca.pem
  foreman_ssl_cert: /etc/foreman-proxy/foreman_ssl_cert.pem
  foreman_ssl_key: /etc/foreman-proxy/foreman_ssl_key.pem
puppet: false
certs:
  generate: false
  deploy: true
capsule:
  puppet: true
foreman::plugin::bootdisk: false
foreman::plugin::chef: false
foreman::plugin::default_hostgroup: false
foreman::plugin::dhcp_browser: false
foreman::plugin::digitalocean: false
foreman::plugin::discovery: false
foreman::plugin::docker: false
foreman::plugin::openscap: false
foreman::plugin::ovirt_provision: false
foreman::plugin::tasks: false
foreman::plugin::hooks: false
foreman::plugin::puppetdb: false
foreman::plugin::remote_execution: false
foreman::plugin::salt: false
foreman::plugin::setup: true
foreman::plugin::templates: false
foreman::compute::ec2: false
foreman::compute::gce: false
foreman::compute::libvirt: false
foreman::compute::openstack: false
foreman::compute::ovirt: false
foreman::compute::rackspace: false
foreman::compute::vmware: false
foreman_proxy::plugin::abrt: false
foreman_proxy::plugin::chef: false
foreman_proxy::plugin::dns::powerdns: false
foreman_proxy::plugin::dynflow: false
foreman_proxy::plugin::openscap: false
foreman_proxy::plugin::pulp:
  enabled: false
  pulpnode_enabled: true
foreman_proxy::plugin::remote_execution::ssh: false
foreman_proxy::plugin::salt: false

