---
version: 5
defaults:
  datadir: foreman.hiera
  data_hash: yaml_data
hierarchy:
  - name: "Custom user answers"
    path: "custom.yaml"
  - name: "Kafo Answers"
  - name: "Built in"
    paths:
      - "family/%{facts.os.family}-%{facts.os.release.major}.yaml"
      - "family/%{facts.os.family}.yaml"
      - "security.yaml"
      - "tuning.yaml"
      - "common.yaml"
