---
version: 5
defaults:
  datadir: foreman.hiera
  data_hash: yaml_data
hierarchy:
  - name: "Enforced scenario overrides"
    path: "scenario/%{facts.kafo.scenario.id}/enforced-scenario-overrides.yaml"
  - name: "Custom user answers"
    path: "custom.yaml"
  - name: "Scenario overrides"
    path: "scenario/%{facts.kafo.scenario.id}/scenario-overrides.yaml"
  - name: "Kafo Answers"
    path: "%{facts.kafo.scenario.answer_file}"
  - name: "Built in"
    paths:
      - "scenario/%{facts.kafo.scenario.id}/family/%{facts.os.family}-%{facts.os.release.major}.yaml"
      - "family/%{facts.os.family}-%{facts.os.release.major}.yaml"
      - "family/%{facts.os.family}.yaml"
      - "security.yaml"
      - "tuning/sizes/%{facts.kafo.scenario.custom.tuning}.yaml"
      - "tuning/common.yaml"
      - "common.yaml"
