---
:name: Foreman Proxy
:description: Install a stand-alone Foreman Proxy

:log_dir: './_build/'
:log_name: 'foreman-proxy.log'
:log_level: DEBUG
:verbose: true
:verbose_log_level: notice

:answer_file: ./config/foreman-proxy-answers.yaml
:installer_dir: .
:module_dirs: ./_build/modules
:parser_cache_path: ./_build/parser_cache/foreman-proxy.yaml
:hiera_config: ./config/foreman-hiera.yaml

:order:
  - foreman_proxy
  - puppet
:low_priority_modules:
  - foreman_proxy_plugin

# If using the Debian ruby-kafo package, uncomment this
# :kafo_modules_dir: /usr/lib/ruby/vendor_ruby/kafo/modules

# Unused, but remains present for older config migrations
:mapping: {}
