## Installer configuration
# Path to answer file
:answer_file: ./config/pulp-answers.yaml
:installer_dir: .
# Uncomment if you want to load puppet modules from a specific path, $pwd/modules is used by default
:module_dirs: ./_build/modules
:hiera_config: ./config/foreman-hiera.yaml
# Location of an optional cache of parsed module data, generate with kafo-export-params -f parsercache
:parser_cache_path: ./_build/parser_cache/pulp.yaml

## Useful for development, e.g. when you want to move log files to local directory
:log_dir: './_build/'
:log_name: 'pulp.log'
:log_level: :debug
:verbose: true
:verbose_log_level: notice

## Kafo tuning, customization of core functionality
:name: Pulp
:description: Standalone installation of Pulp
